[project]
name = "simple-form-backend"
version = "0.1.0"
requires-python = "==3.12.*"
dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "motor",
    "pydantic"
]

[tool.uv]
# Use Python 3.12 environment
python = "3.12"
